name: Python Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest and Coverage
        run: |
          pip install coverage
          pytest tests --cov=src --cov-branch
        env:
          CI: true

      - name: Check Branch Coverage
        run: |
          coverage report --fail-under=75
        env:
          CI: true
